chdir D:\sources\
echo OOBE Skipper is using DISM to image the HDD with Windows 10...
dism /apply-image /imagefile:install.wim /index:1 /applydir:C:\
echo OOBE Skipper is creating important boot files...
bcdboot C:\Windows /s W:
echo OOBE Skipper is loading registry hives...
reg load HKLM\SOFT C:/Windows/system32/config/SOFTWARE
reg load HKLM\SYS C:/Windows/system32/config/SYSTEM
echo OOBE Skipper is editing the registry...
regedit /s D:\OOBESkipper\registry\registrymodule1.reg
echo OOBE Skipper is rebooting Setup... Windows will need to take a bit before the next batch file loads in.
wpeutil reboot
